<a href="https://colab.research.google.com/github/LuaraEv04/lua.ipynb/blob/main/LuaraEv_Aula06_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install pydicom

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.3 MB/s eta 0:00:00


In [ ]:
#usar **.array para descobrir a matriz solicitada
import numpy
numpy.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
#import somente para abreviar a função numpy
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
#from para importar sem abreviação
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [ ]:
import numpy as np
fam = ['Liz', 1.73, 'ema', 1.68, 'mom', 1.71, 'dad', 1.89]
print(fam)
print(type(fam))
fam_ext = fam + ['me', 1.79]
print(fam_ext)
print(type(fam_ext))
print(str(len(fam_ext)) + 'elements in fam_ext')
np_fam = np.array(fam_ext)

['Liz', 1.73, 'ema', 1.68, 'mom', 1.71, 'dad', 1.89]
<class 'list'>
['Liz', 1.73, 'ema', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]
<class 'list'>
10elements in fam_ext


In [ ]:
#Definition of radius 
r = 0.43
#Import the math package
import math 
#Calcule C
C = 2* math.pi*2
#Calcule A
A = math.pi*r**2
#Biuld printout
print('Circunferência' + str(C))
print('Área' + str(A))

Circunferência12.566370614359172
Área0.5808804816487527


In [ ]:
height = [1.79, 1.65, 1.84, 1.58, 1.69]
print(height)
weight = [75.0, 66.4, 84.7, 62.8, 68.3]
print(weight)

[1.79, 1.65, 1.84, 1.58, 1.69]
[75.0, 66.4, 84.7, 62.8, 68.3]


In [ ]:
import numpy as np
np_height = np.array(height)
print(np_height)
np_weight = np.array(weight)
print(np_weight)
bmi = np_weight / np_height**2
print(bmi)

[1.79 1.65 1.84 1.58 1.69]
[75.  66.4 84.7 62.8 68.3]
[23.40750913 24.38934803 25.01772212 25.15622496 23.91372851]


In [ ]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
print(bmi)
print(bmi[1])
print(bmi > 24)
bmi[bmi > 24]

[23.40750913 24.38934803 25.01772212 25.15622496 23.91372851]
24.389348025711666
[False  True  True  True False]


array([24.38934803, 25.01772212, 25.15622496])

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [ ]:
np_2d.shape
#2 linhas e 5 colunas

(2, 5)

In [ ]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
         [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [ ]:
# np de 3 linhas e 5 colunas
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7],
                 [18.6, 14.6, 17.8, 21.7, 34.8]])
print(np_3d.shape)

(3, 5)


In [ ]:
# np de 3 linhas e 3 colunas 
np_3xd = np.array([[1.73, 1.71, 1.79],
                   [65.4, 63.6, 68.7],
                   [18.6, 17.8, 34.8]])
print(np_3xd.shape)

(3, 3)


In [ ]:
#encontrar um número em determinada posição
np_2d[0][2]

1.71

In [ ]:
np_2d[0,2]

1.71

In [ ]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [ ]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
# creat list baseball
baseball = [180, 215, 210, 210,
            188, 176, 209, 200]
# import the numpy package as np
import numpy as np
# creat nump array from baseball
np_baseball = np.array(baseball)
# print out type of baseball
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)


In [ ]:
import random as rd
import numpy as np 
# geração de números entre 150 e 209
height = range(150, 210)
print(height)
#geração de números entre 50 e 149
weight = range(50, 150)
print(weight)
#amostra randomica de 20 números de weight 
height = rd.sample(height,20)
print(height)
#amostra randomica de 20 números de weight
weight = rd.sample(weight,20)
print(weight)

range(150, 210)
range(50, 150)
[153, 189, 207, 163, 171, 187, 199, 201, 150, 202, 181, 182, 168, 169, 155, 204, 205, 170, 180, 178]
[78, 83, 54, 89, 104, 50, 81, 95, 101, 108, 69, 133, 64, 96, 121, 124, 66, 126, 107, 75]


In [ ]:
#converta height em array e normalize multiplicando por 0.01
height_array = np.array(height)*0.01
print(height_array)
#converta weight em array 
weight_array = np.array(weight)
print(weight_array)
#calcule bmi 
bmi = weight_array/height_array**2
print(bmi)
#verifique onde bmi é menor que 21
light = bmi<21
print(light)
#exiba os valores de bmi onde bmi é maior que 21
print(bmi[bmi<21])
#print os elementos de weight_array do index 8 até o index 15, incluindo o 15
print(weight_array[8:16])
#print os elementos de height_array do index 11 até o index 19, incluindo o 19
print(height_array[11:20])

[1.77 1.52 1.75 1.7  2.02 2.01 1.83 1.72 1.68 1.89 1.78 1.66 1.88 1.86
 1.96 1.92 1.53 1.69 1.84 1.91]
[ 91  86  85 121 124 100  50  84  67 138  60 115  65  78 122 106  96 113
 114 135]
[29.04657027 37.22299169 27.75510204 41.86851211 30.38917753 24.75186258
 14.93027561 28.39372634 23.73866213 38.63273705 18.9370029  41.73319785
 18.39067451 22.54595907 31.757601   28.75434028 41.009868   39.56444102
 33.67202268 37.00556454]
[False False False False False False  True False False False  True False
  True False False False False False False False]
[14.93027561 18.9370029  18.39067451]
[ 67 138  60 115  65  78 122 106]
[1.66 1.88 1.86 1.96 1.92 1.53 1.69 1.84 1.91]


In [ ]:
#creat baseball, list of list 
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
print(baseball)
# import nump 
import numpy as np
#creat np_baseball (2 cols)
np_baseball = np.array(baseball)
print(np_baseball)
# print terceira linha na linha código 14
print(np_baseball[2])
#crie uma nova variável np_weight que receba toda a segunda coluna de np_baseball
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)
#print a primeira coluna da segunda linha de np_baseball
np_weight_lb = np_baseball[1,0]
print(np_weight_lb)

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
[210.   98.5]
[ 78.4 102.7  98.5  75.2]
215.0
